#!/bin/sh
#PBS -l nodes=2:ppn=32
#PBS -l walltime=01:00:00
#PBS -q express
#PBS -M <login>@i10.informatik.uni-erlangen.de -m abe
#PBS -N Test5_SLMC_200x200

. /etc/profile.d/modules.sh
module load gcc openmpi cuda boost cmake

cd /home/stud/ug30owag/Documents/GMRF_PETSc
#mpirun -np 32 ./test_PDE -mat_type mpiaij -vec_type mpi -ksp_monitor_short -pc_type hypre -ksp_type fgmres -ksp_gmres_modifiedgramschmidt -m 10000 -n 10000
mpiexec -np 16 ./Test5 -mat_type mpiaij -vec_type mpi -Nsamples 100000 -m 200 -n 200 -pc_type hypre -ksp_type fgmres -dim 2 -alpha 2 -lamb 0.1 -sigma 0.3 -TOL 1e-3
